CREATE SCHEMA IF NOT EXISTS contentdb;
USE contentdb;
DROP TABLE IF EXISTS contents;

CREATE TABLE IF NOT  EXISTS contents (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  curriculum VARCHAR(255) NOT NULL,
  content VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
